### ISSUE TITLE
Generate dynamic spiders from *.yml file 

### ISSUE THREAD

**Issue by GustavoRPS** [Labic/ze-the-scraper#3]
Proposed structure:
```yml
name: g1
allowed_domains:
  - g1.globo.com
items:
  ze.items.creativework.ArticleItem: 
    rules: []
    fields: 
      name:
        - [itemprop=name]::text 
        - .content-head__title::text 
      image: 
        - [itemprop=image]::attr(content) 
        - [property='og:image']::attr(content) 
      description:: 
          - [itemprop=description]::text
          - [itemprop=alternativeHeadline]::text
          - .content-head__subtitle::text 
      author: 
          - [itemprop=author]::text
          - [itemprop=creator]::text
      datePublished: 
          - [itemprop=datePublished]::text
          - [itemprop=datePublished]::attr(datetime)
      dateModified: 
          - [itemprop=dateModified]::text
          - [itemprop=dateModified]::attr(datetime)
      articleBody: 
          - [itemprop=articleBody]
          - .mc-body 
      keywords: 
          - [itemprop=keywords]::text
          - .entities__list-itemLink::text
```
